### ISSUE TITLE
ERROR: Input taxid not within supported range. (taxid 7604)

### ISSUE THREAD

**Issue by richard-burhans** [ncbi/egapx#79]
I'm using EGAPx version 0.3.2-alpha with the following configuration:
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/459/465/GCF_902459465.1_eAstRub1.3/GCF_902459465.1_eAstRub1.3_genomic.fna.gz
taxid: 7604
reads:
 - SRR1139190
 - SRR1685733
 - SRR3087891
 - SRR10202062
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_902459465.1
locus_tag_prefix: egapxtmp
```
I'm getting the following error:
```
ERROR: Input taxid not within supported range. Must be under Arthropoda(6656), Vertebrata(7742), or Magnoliopsida(3398) according to NCBI Taxonomy (https://www.ncbi.nlm.nih.gov/taxonomy)
```
Is this expected?
