### ISSUE TITLE
Some egapx:rnaseq_short_plane:star:run_star jobs fail within about a minute of starting

### ISSUE THREAD

**Issue by richard-burhans** [ncbi/egapx#80]
I have six examples where egapx:rnaseq_short_plane:star:run_star is failing shortly after starting with errors like the following:
```
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "/path/to/file.bam"

star_wnode Error: STAR(CException::eUnknown) "STAR_wnode.cpp", line 208: ncbi::CGPX_STARJob::Process() --- sorting job failed for SRR030395
star_wnode Error: LIB "wn_worker_thread.cpp", line 267: ncbi::CWorkerThread::x_DoJob() --- error processing job: (CException::eUnknown) sorting job failed for SRR030395

star_wnode Error: LIB(CException::eUnknown) "wn_app_core.cpp", line 256: ncbi::CGPX_WorkerAppCore::Run() --- 1 jobs failed
star_wnode Error: CORELIB(106.16) "ncbiapp.cpp", line 699: ncbi::CNcbiApplicationAPI::x_TryMain() --- Application's execution failed (CException::eUnknown) 1 jobs failed
```
Here are the configurations:
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/769/535/GCF_009769535.1_rThaEle1.pri/GCF_009769535.1_rThaEle1.pri_genomic.fna.gz
taxid: 35005
reads:
 - SRR030394
 - SRR030395
 - SRR497737
 - SRR497738
 - SRR497739
 - SRR497740
 - SRR497741
 - SRR497742
 - SRR497743
 - SRR497744
 - SRR497746
 - SRR497747
 - SRR497748
 - SRR497749
 - SRR629599
 - SRR629651
 - SRR629652
 - SRR629653
 - SRR629654
 - SRR629655
 - SRR629656
 - SRR629657
 - SRR629658
 - SRR629659
 - SRR629661
 - SRR629660
 - SRR629662
 - SRR629664
 - SRR629663
 - SRR629665
 - SRR629666
 - SRR629667
 - SRR629668
 - SRR629669
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_009769535.1
locus_tag_prefix: egapxtmp
```
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/028/885/625/GCF_028885625.2_NHGRI_mPonPyg2-v2.0_pri/GCF_028885625.2_NHGRI_mPonPyg2-v2.0_pri_genomic.fna.gz
taxid: 9600
reads:
 - DRR128393
 - DRR128394
 - DRR128395
 - SRR306791
 - SRR306792
 - SRR306793
 - SRR306794
 - SRR306795
 - SRR306796
 - SRR306797
 - SRR306798
 - SRR306799
 - SRR2176206
 - SRR2176207
 - SRR8711714
 - SRR17715153
 - SRR17715148
 - SRR25032598
 - SRR25032599
 - SRR25032600
 - SRR25032601
 - SRR27178657
 - SRR22452369
 - SRR27178658
 - SRR27178659
 - SRR27438214
 - SRR27438215
genome_size_threshold: 4000000000
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
  star_index:
      STAR: --runThreadN 8
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_028885625.2
locus_tag_prefix: egapxtmp
```
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/227/805/GCF_015227805.2_bHirRus1.pri.v3/GCF_015227805.2_bHirRus1.pri.v3_genomic.fna.gz
taxid: 43150
reads:
 - SRR13516427
 - SRR13516426
 - SRR13516425
 - SRR10853074
 - SRR9184408
 - SRR9184409
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_015227805.2
locus_tag_prefix: egapxtmp
```
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/028/018/845/GCF_028018845.1_bMelGeo1.pri/GCF_028018845.1_bMelGeo1.pri_genomic.fna.gz
taxid: 44398
reads:
 - SRR1198302
 - SRR1198303
 - SRR1198305
 - SRR1198306
 - SRR1198308
 - SRR1198307
 - SRR1198320
 - SRR393822
 - SRR393823
 - SRR500996
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_028018845.1
locus_tag_prefix: egapxtmp
```
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/029/289/425/GCF_029289425.2_NHGRI_mPanPan1-v2.0_pri/GCF_029289425.2_NHGRI_mPanPan1-v2.0_pri_genomic.fna.gz
taxid: 9597
reads:
 - SRR873627
 - SRR873628
 - SRR873626
 - SRR873629
 - SRR8750597
 - SRR8750443
 - SRR8750603
 - SRR8750612
 - SRR8750618
 - SRR8750630
 - SRR8750410
 - SRR8750425
 - SRR8750615
 - SRR8750419
 - SRR8750422
 - SRR8750398
 - SRR27178652
 - SRR27438210
 - SRR27438211
genome_size_threshold: 4000000000
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
  star_index:
      STAR: --runThreadN 8
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_029289425.2
locus_tag_prefix: egapxtmp
```
```yaml
genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/964/775/GCF_900964775.1_fSclFor1.1/GCF_900964775.1_fSclFor1.1_genomic.fna.gz
taxid: 113540
reads:
 - SRR941557
 - SRR941783
 - SRR941784
 - SRR941785
 - SRR3309317
 - SRR3309318
 - SRR3309319
 - SRR3309320
 - SRR3309321
 - SRR3309322
 - SRR3309323
tasks:
  gnomon:
      gnomon_biotype:
          gnomon_biotype: -max_prok_hits_pct 75
annotation_provider: GenBank submitter
annotation_name_prefix: GCF_900964775.1
locus_tag_prefix: egapxtmp
```
